### ISSUE TITLE
Support smol async runtime

### ISSUE THREAD

**Issue by mmstick** [algesten/hreq#1]
Perhaps more in line with the idea of having a small async HTTP client. Doesn't depend on mio, implementation is significantly simpler than tokio and async-std, and only contains safe Rust.

- https://github.com/stjepang/smol
- [Example HTTP+TLS client](https://github.com/stjepang/smol/blob/master/examples/async-h1-client.rs)

**Comment by algesten** [comment]
I'm totally into this idea. I'll take a look this weekend. thanks!

**Comment by algesten** [comment]
I've been just looking at dependency tree. One problem I have is that `smol` would mean going from 89 dependencies (with default features), to 114.

The underlying issue is that with the [h2 crate](https://crates.io/crates/h2), we always drag in a bunch of tokio dependencies also when we're not using the tokio runtime.

That means we're effectively always "paying the price" for some subset of tokio, and the difference to using a complete tokio runtime is less. I'm toying with the idea of forking h2 to some "runtime free" variant.

```
4a5
> async-task v3.0.0
8a10
> bitflags v1.2.1
15a18,23
> crossbeam v0.7.3
> crossbeam-channel v0.4.2
> crossbeam-deque v0.7.3
> crossbeam-epoch v0.8.2
> crossbeam-queue v0.2.1
> crossbeam-utils v0.7.2
41a50
> maybe-uninit v2.0.0
42a52
> memoffset v0.5.4
44,45c54
< mio v0.6.22
< net2 v0.2.34
---
> nix v0.17.0
52a62
> piper v0.1.2
65a76,77
> scoped-tls-hkt v0.1.2
> scopeguard v1.1.0
70a83,84
> smol v0.1.10
> socket2 v0.3.12
87a102
> void v1.0.2
```

**Comment by algesten** [comment]
After a day of reducing dependencies (I have a a tokio free h2 here https://github.com/algesten/h2), I did some counting.

Without any runtime installed, I am now at 65 dependencies.

```
$ cargo tree --no-dev-dependencies --no-indent | sort | grep -v \* | wc -l
      65
```

Adding back a minimal tokio:

```
tokio-lib = { package = "tokio", version = "0.2", default-features = false, features = ["rt-core", "tcp", "dns", "time", "fs"], optional = true }
```

we get 70 dependencies.

However with smol we get 83.

Smol might be a small runtime in terms of LOC in the module itself, but it pulls in a lot of other deps:

```
├── smol v0.1.10
│   ├── async-task v3.0.0
│   ├── crossbeam v0.7.3
│   │   ├── cfg-if v0.1.10 (*)
│   │   ├── crossbeam-channel v0.4.2
│   │   │   ├── crossbeam-utils v0.7.2
│   │   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   │   └── lazy_static v1.4.0
│   │   │   │   [build-dependencies]
│   │   │   │   └── autocfg v1.0.0 (*)
│   │   │   └── maybe-uninit v2.0.0
│   │   ├── crossbeam-deque v0.7.3
│   │   │   ├── crossbeam-epoch v0.8.2
│   │   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   │   ├── crossbeam-utils v0.7.2 (*)
│   │   │   │   ├── lazy_static v1.4.0 (*)
│   │   │   │   ├── maybe-uninit v2.0.0 (*)
│   │   │   │   ├── memoffset v0.5.4
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.0.0 (*)
│   │   │   │   └── scopeguard v1.1.0
│   │   │   │   [build-dependencies]
│   │   │   │   └── autocfg v1.0.0 (*)
│   │   │   ├── crossbeam-utils v0.7.2 (*)
│   │   │   └── maybe-uninit v2.0.0 (*)
│   │   ├── crossbeam-epoch v0.8.2 (*)
│   │   ├── crossbeam-queue v0.2.1
│   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   └── crossbeam-utils v0.7.2 (*)
│   │   └── crossbeam-utils v0.7.2 (*)
```

Compare this with the minimal tokio:

```
├── tokio v0.2.21
│   ├── bytes v0.5.4 (*)
│   ├── iovec v0.1.4
│   │   └── libc v0.2.70 (*)
│   ├── lazy_static v1.4.0
│   ├── memchr v2.3.3 (*)
│   ├── mio v0.6.22
│   │   ├── cfg-if v0.1.10 (*)
│   │   ├── iovec v0.1.4 (*)
│   │   ├── libc v0.2.70 (*)
│   │   ├── log v0.4.8 (*)
│   │   ├── net2 v0.2.34
│   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   └── libc v0.2.70 (*)
│   │   └── slab v0.4.2 (*)
│   ├── pin-project-lite v0.1.5 (*)
│   └── slab v0.4.2 (*)
```

**Comment by mmstick** [comment]
Number of dependencies has never been a concern to me. It's honestly not a very useful metric in terms of complexity.

**Comment by algesten** [comment]
I think number of dependencies can be somewhat of a concern.

* Compile time. Sure there are other factors that can matter more, like heavy use of generics.
* Security. No one reviews every dep pulled in.
* Bloated binary. Having half of tokio pulled in also when my runtime of choice is something else.

My background is in NodeJS, and I run screaming from that scenario. Never again do I want to be close to things like "ava" (a test runner that claims to be "minimal and fast"), which has over [200 dependencies](http://npm.broofa.com/?q=ava).

**Comment by algesten** [comment]
I've pushed 0.2.0 which has smol as an optional runtime. I was looking at making it the default, however my gut feeling is that tokio is still rather dominant, and even though I like the idea of no unsafe and simplicity, the default features should probably support the most common use case.
