### ISSUE TITLE
Panic on some websites: "Incoming body is not valid utf-8"

### ISSUE THREAD

**Issue by Shnatsel** [algesten/hreq#38]
On some websites, e.g. http://netclusive.de, hreq panics with the following message:

> thread 'main' panicked at 'Incoming body is not valid utf-8: FromUtf8Error { bytes: [ /* byte dump omitted */ ], error: Utf8Error { valid_up_to: 9701, error_len: Some(1) } }', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/hreq-0.7.1/src/body.rs:676:35

25718 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/src/main.rs). Test tool output for all occurrences is too large to post here, but here's a list of domains where it happened: [hreq-utf8-panic-domain-list.txt.gz](https://github.com/algesten/hreq/files/6192564/hreq-utf8-panic-domain-list.txt.gz)

**Comment by algesten** [comment]
Hi @Shnatsel - You found my Other Project? ;)

Always grateful for your reports. Improving quality. Thanks, I'll look into this problem.

**Comment by Shnatsel** [comment]
Yup! It's been on my radar for a while. I've run all the tests at roughly the same time, but I got around to analyzing the results for hreq only now.
