### ISSUE TITLE
Panic on some websites: 'assertion failed: sz <= self.window_size'

### ISSUE THREAD

**Issue by Shnatsel** [algesten/hreq#39]
On some websites, e.g. http://zzzebra.de, hreq panics with the following message:

> 'assertion failed: sz <= self.window_size', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/hreq-h2-0.2.7/src/proto/streams/flow_control.rs:176:9

2130 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/src/main.rs). Test tool output for all occurrences: [hreq-window-size-panic.tar.gz](https://github.com/algesten/hreq/files/6192595/hreq-window-size-panic.tar.gz)

**Comment by algesten** [comment]
Hm hm.. I see hreq-h2 🤔 Is this really running against latest?

I've linked hreq directly to h2 now, not using my hreq-h2 wrapper atm.

**Comment by Shnatsel** [comment]
I've run the test roughly a month ago, so probably not. Here's the Cargo.lock I used so you could look up the exact versions: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/Cargo.lock

**Comment by algesten** [comment]
Makes sense. I'll check whether this still happens on the latest release.

**Comment by algesten** [comment]
I've tested about 10 of the example failing urls, and they all work now. I think this is fixed.
