### ISSUE TITLE
panic 'year must be in the range -100000..=100000' on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/hreq#40]
When downloading http://guaranteedrate.com, hreq panics with the following message:

> guaranteedrate.com:thread 'main' panicked at 'year must be in the range -100000..=100000', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.25/src/date.rs:711:25

Three websites out of the top million according to [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/src/main.rs). Test tool output for all affected websites: [hreq-year-out-of-range.tar.gz](https://github.com/algesten/hreq/files/6192725/hreq-year-out-of-range.tar.gz)

**Comment by Shnatsel** [comment]
Oops, there are actually 3 instances of this panic. Updated description & attached archive.

**Comment by algesten** [comment]
Some sites return a cookie life time that makes `Duration` fail.
