### ISSUE TITLE
"http api: invalid format" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/hreq#44]
On some websites, e.g. http://festival-piano.com, hreq fails with the following error:

> http api: invalid format

Firefox and curl work fine.

1554 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/src/main.rs) and [this `Cargo.lock`](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/Cargo.lock). Test tool output for all occurrences: [hreq-invalid-format.tar.gz](https://github.com/algesten/hreq/files/6242170/hreq-invalid-format.tar.gz)

**Comment by algesten** [comment]
This was due to a problem with interpreting path relative redirects on the form "foo/"

**Comment by algesten** [comment]
And a bunch of other cases. Like redirects to just a scheme, "https://" or using too many slashes "https:///foo.bar"
