### ISSUE TITLE
"proto: Failed to parse 'index.html' relative to: index.html" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/hreq#47]
On some websites, e.g. http://emland.net, hreq fails with the following error:

> proto: Failed to parse 'index.html' relative to: index.html

The exact path can be other than `index.html`, but the two paths seem to always be the same.

Firefox, curl and reqwest (with rustls) work fine.

1563 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/src/main.rs) and [this `Cargo.lock`](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/Cargo.lock). Test tool output for all occurrences: [hreq-failed-to-parse-relative-to.tar.gz](https://github.com/algesten/hreq/files/6242359/hreq-failed-to-parse-relative-to.tar.gz)

**Comment by algesten** [comment]
This seems to behave now. Most likely down to 413a1a0 and 24c46ce
